language: ruby
rvm:
  - 1.9.3
bundler_args: --without development:production --path=.bundle/gems
before_script:
  - RAILS_ENV=test rake db:create db:migrate --quiet
  - "export DISPLAY=:100.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
